# This is a basic workflow to help you get started with Actions

name: CreaInfraTerraform-aplica

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY_ID }}
          aws-region: us-east-1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0 # Cambia a la versión de Terraform que estés utilizando

      - name: Terraform init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Descargar archivo desde GitHub
        run: curl -o index.html https://raw.githubusercontent.com/user/repo/main/index.html

      - name: Cargar archivo a S3
        run: aws s3 cp index.html s3://bucket-proyfinal-devops-0209/
